search_input = "[type='search']"
search_button = "div input[type='submit']"
page_header = ".page-header h1"
search_elements = ".product_pod"
book_title = ".product_pod h3"
book_img = ".product_pod img"
book_price = ".product_pod .product_price .price_color"

catalog_menu = "ul .dropdown-menu :nth-child(1)"
add_product_button = "[action='/ru/basket/add/207/']"
cart_button = "[href='/ru/basket/'"
products_in_cart = ".basket-items"
name_product_cart = ".basket-items .col-sm-4 a"
amount_product_cart = ".basket-items [type='number']"
price_product_cart = ".price_color"
image_product_cart = ".basket-items img"

main_page = "http://selenium1py.pythonanywhere.com/"
search_text = "Coders at work"
book_name = "Coders at Work"
price = "19,99"

login_link = "#login_link"
person_name = "#id_login-username"
person_pswd = "#id_login-password"
sign_in_button = "[name='login_submit']"
account_page_link = "[href='/ru/accounts/']"
email_page_link = "[href='/ru/accounts/emails/']"
first_email_link = ".table tbody tr:nth-child(1) a"
page_title_text = ".page-header h1"
topic_email_text = ".table tr:nth-child(2) td"
description_email_text = ".table tr:nth-child(3) td"

email = "la+1@mail.com"
user_pswd = "Stepik0987"

catalog_link = "ul .dropdown-menu :nth-child(1)"
add_product_button = "[action='/ru/basket/add/207/']"
cart_link = "[href='/ru/basket/'"
checkout_button = ".form-group [href='/ru/checkout/']"
user_name_input = "#id_username"
login_radio_button = "[for='id_options_2']"
user_pswd_input = "#id_password"
login_button = ".form-stacked button"
f_name_input = "#id_first_name"
l_name_input = "#id_last_name"
first_line_input = "#id_line1"
city_input = "#id_line4"
postcode_input = "#id_postcode"

profile_edit_link = "[href='/ru/accounts/profile/edit/']"
email_imput = "#id_email"
new_email = "la+2@mail.com"
save_edited_profile = "#profile_form button"
success_editing_text = ".alertinner"
profile_email_labbel = ".table tr:nth-child(2) td"

item_buy_button = "#add_to_basket_form button"

registration_email_input = "#id_registration-email"
registration_pswd_input1 = "#id_registration-password1"
registration_pswd_input2 = "#id_registration-password2"
registration_button = "[name='registration_submit']"
registration_email = "la+10@mail.com"
success_registration_alert = ".alertinner"



